export default [
    {
        name: 'Chapter 1',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-1.pdf",
        description: '#a8edea → #fed6e3',
        css: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
        height: 200,
    },
    {
        name: 'Chapter 2',
        description: '#f5f7fa → #c3cfe2',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-2.pdf",
        css: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
        height: 400,
    },
    {
        name: 'Chapter 3',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-3.pdf",
        description: '#e0c3fc → #8ec5fc',
        css: 'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)',
        height: 400,
    },
    {
        name: 'Chapter 4',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-4.pdf",
        description: '#f093fb → #f5576c',
        css: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        height: 400,
    },
    {
        name: 'Chapter 5',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-5.pdf",
        description: '#fdfbfb → #ebedee',
        css: 'linear-gradient(135deg, #E3FDF5 0%, #FFE6FA 100%)',
        height: 400,
    },
    {
        name: 'Chapter 6',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-6.pdf",
        description: '#5ee7df → #b490ca',
        css: 'linear-gradient(135deg, #5ee7df 0%, #b490ca 100%)',
        height: 400,
    },
    {
        name: 'Chapter 7',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-7.pdf",
        description: '#d299c2 → #fef9d7',
        css: 'linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)',
        height: 200,
    },
    {
        name: 'Chapter 8',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-8.pdf",
        description: '#ebc0fd → #d9ded8',
        css: 'linear-gradient(135deg, #ebc0fd 0%, #d9ded8 100%)',
        height: 400,
    },
    {
        name: 'Chapter 9',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-9.pdf",
        description: '#f6d365 → #fda085',
        css: 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)',
        height: 200,
    },
    {
        name: 'Chapter 10',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-10.pdf",
        description: '#96fbc4 → #f9f586',
        css: 'linear-gradient(135deg, #96fbc4 0%, #f9f586 100%)',
        height: 400,
    },
    {
        name: 'Chapter 11',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-11.pdf",
        description: ' #FFFEFF → #D7FFFE',
        css: 'linear-gradient(135deg, #FFFEFF 0%, #D7FFFE 100%)',
        height: 200,
    },
    {
        name: 'Chapter 12',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-12.pdf",
        description: ' #fff1eb → #ace0f9',
        css: 'linear-gradient(135deg, #fff1eb 0%, #ace0f9 100%)',
        height: 400,
    },
    {
        name: 'Chapter 13',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-13.pdf",
        description: ' #c1dfc4 → #deecdd',
        css: 'linear-gradient(135deg, #c1dfc4 0%, #deecdd 100%)',
        height: 400,
    },
    {
        name: 'Chapter 14',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-14.pdf",
        description: ' #ddd6f3 → #faaca8',
        css: 'linear-gradient(135deg, #ddd6f3 0%, #faaca8 100%, #faaca8 100%)',
        height: 200,
    },
    {
        name: 'Chapter 15',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-15.pdf",
        description: '#a8edea → #fed6e3',
        css: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
        height: 200,
    },
    {
        name: 'Chapter 16',
        description: '#f5f7fa → #c3cfe2',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-16.pdf",
        css: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
        height: 400,
    },
    {
        name: 'Chapter 17',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-17.pdf",
        description: '#e0c3fc → #8ec5fc',
        css: 'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)',
        height: 400,
    },
    {
        name: 'Chapter 18',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-18.pdf",
        description: '#f093fb → #f5576c',
        css: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        height: 400,
    },
    {
        name: 'Chapter 19',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-19.pdf",
        description: '#fdfbfb → #ebedee',
        css: 'linear-gradient(135deg, #E3FDF5 0%, #FFE6FA 100%)',
        height: 400,
    },
    {
        name: 'Chapter 20',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-20.pdf",
        description: '#5ee7df → #b490ca',
        css: 'linear-gradient(135deg, #5ee7df 0%, #b490ca 100%)',
        height: 400,
    },
    {
        name: 'Chapter 21',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-21.pdf",
        description: '#d299c2 → #fef9d7',
        css: 'linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)',
        height: 200,
    },
    {
        name: 'Chapter 22',
        path: "/wp-content/themes/logistic/pdfs/import/chapter-22.pdf",
        description: '#ebc0fd → #d9ded8',
        css: 'linear-gradient(135deg, #ebc0fd 0%, #d9ded8 100%)',
        height: 400,
    },
]
